### ISSUE TITLE
滚动的逻辑有点问题

### ISSUE THREAD

**Issue by TtlyLynzie** [l1xnan/weread#26]
点击停止滚动按钮后，如果想要再重新开始滚动，就只能点击上面的那个开始滚动，但是滚动速度会增加

**Comment by l1xnan** [comment]
这个功能我自己用的比较少，大致梳理了下，应该是有一个按钮专门控制滚动启停，一个按钮专门调整滚动速度，现在两个按钮设计有点拧巴。你希望点击停止的时候，速度重置为 x1，还是保留上一次的滚动速度，我给改下?

**Comment by TtlyLynzie** [comment]
感觉保留上次的滚动速度比较好？

**Comment by l1xnan** [comment]
那 0.0.7 版本应该就可以了，目前看第1级滚动速度不算太慢，阅读还是有点吃力，10级滚速也有点多，需要调整下，缺少自动翻页到下一章功能
